[package]
name = "tokio-io-timeout"
version = "0.4.0-alpha.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Tokio wrappers which apply timeouts to IO operations"
repository = "https://github.com/sfackler/tokio-io-timeout"
readme = "README.md"
edition = "2018"

[dependencies]
bytes = "0.4.4"
tokio-timer = "=0.3.0-alpha.4"
tokio-io = "=0.2.0-alpha.4"

[dev-dependencies]
tokio = "=0.2.0-alpha.4"
