[package]
name = "tokio-io-timeout"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Tokio wrappers which apply timeouts to IO operations"
repository = "https://github.com/sfackler/tokio-io-timeout"
documentation = "https://docs.rs/tokio-io-timeout/0.1.0/tokio_io_timeout"
readme = "README.md"

[dependencies]
bytes = "0.4.4"
futures = "0.1.14"
tokio-core = "0.1.7"
tokio-io = "0.1.2"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
