restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index
deps_key: &DEPS_KEY
  key: deps-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
restore_deps: &RESTORE_DEPS
  restore_cache:
    <<: *DEPS_KEY
save_deps: &SAVE_DEPS
  save_cache:
    <<: *DEPS_KEY
    paths:
    - target
    - /usr/local/cargo/registry/cache

version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: rust:latest
        environment:
          RUSTFLAGS: -D warnings
    steps:
      - checkout
      - run: rustup toolchain install nightly
      - *RESTORE_REGISTRY
      - run: rustup run nightly cargo generate-lockfile
      - *SAVE_REGISTRY
      - run: rustup run nightly rustc --version > ~/rust-version
      - *RESTORE_DEPS
      - run: rustup run nightly cargo test
      - *SAVE_DEPS
